[package]
name = "knee-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
fs = "0.0.5"
futures = "0.3.30"
rand = "0.8.5"
regex = "1.10.6"
reqwest = "0.12.7"
scraper = "0.20.0"
tokio = { version = "1.40.0", features = ["full", "fs"] }
url = "2.5.2"
